# myQuant系统配置文件
# 数据管理器配置
data_manager:
  db_path: "./data/myquant.db"
  cache_size: 1000
  cache_ttl: 3600

# 策略引擎配置
strategy_engine:
  max_strategies: 10
  event_queue_size: 1000
  enable_logging: true
  thread_pool_size: 4

# 回测引擎配置
backtest_engine:
  initial_capital: 1000000
  commission_rate: 0.0003
  slippage_rate: 0.001
  min_commission: 5.0
  frequency: "daily"

# 投资组合管理器配置
portfolio_manager:
  initial_capital: 1000000
  base_currency: "CNY"
  commission_rate: 0.0003
  min_commission: 5.0
  min_position_value: 1000
  max_positions: 50
  cash_buffer: 0.05
  rebalance_frequency: "monthly"
  rebalance_threshold: 0.05

# 风险管理器配置
risk_manager:
  max_position_size: 0.1
  max_drawdown_limit: 0.2
  var_confidence: 0.95
  max_daily_trades: 100
  max_order_size: 0.05
  enable_dynamic_limits: true

# 订单管理器配置
order_manager:
  max_orders_per_second: 10
  max_pending_orders: 100
  order_timeout: 3600
  max_daily_orders: 1000

# 绩效分析器配置
performance_analyzer:
  risk_free_rate: 0.03
  trading_days_per_year: 252
  confidence_levels: [0.95, 0.99]
  benchmark_symbol: "000001.SH"

# 异步数据引擎配置
async_data_engine:
  max_concurrent_requests: 10
  request_timeout: 30
  retry_attempts: 3
  cache_ttl: 300
  rate_limit_per_second: 10